# Generated by Django 4.0.5 on 2022-09-08 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('ordered_image', models.ImageField(upload_to='ordered_images/')),
                ('delivered_image', models.ImageField(upload_to='delivered_images/')),
                ('name', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
                ('availability', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shopping_Cart.customer')),
            ],
        ),
    ]
